### ISSUE TITLE
Add support to latest nodejs version

### ISSUE THREAD

**Issue by gautamkrishnar** [redhataccess/jwt-redhat#56]
The cli is returning the below error when used with node latest version (v14.15.4)

```bash
 gautam  ~  accessproxy
fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/gautam/.nvm/versions/node/v14.15.4/lib/node_modules/accessproxy/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/gautam/.nvm/versions/node/v14.15.4/lib/node_modules/accessproxy/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/gautam/.nvm/versions/node/v14.15.4/lib/node_modules/accessproxy/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by gautamkrishnar** [comment]
Whops wrong repo, closing this one.
